language: rust
rust:
  - stable
  # - beta
  # - nightly

before_script:
  - rustup component add clippy

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo run --example groth16 --release
  - cargo run --example marlin --release

